# Generated by Django 4.2.3 on 2023-07-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klisterApp", "0002_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilePath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=1024)),
            ],
        ),
    ]
