# Generated by Django 4.2.3 on 2023-07-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klisterApp", "0003_filepath"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filepath", old_name="password", new_name="path",
        ),
    ]
