# Generated by Django 4.2.3 on 2023-07-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klisterApp", "0005_spreadsheetid_delete_filepath"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spreadsheetid", old_name="ID", new_name="IDString",
        ),
    ]
