# Generated by Django 4.2.3 on 2023-07-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klisterApp", "0007_delete_spreadsheetid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpreadsheetId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IDString", models.CharField(max_length=1024)),
                ("gid", models.CharField(max_length=1024)),
            ],
        ),
    ]
